### ISSUE TITLE
@SingleClick 可以兼容下 anko 的语法吗？

### ISSUE THREAD

**Issue by palorotolo** [xuexiangjys/XAOP#1]
例如这种 View.onClick{}

**Comment by xuexiangjys** [comment]
可以考虑看看

**Comment by xuexiangjys** [comment]
兼容方案已加上，[详情请点击查看](https://github.com/xuexiangjys/XAOP#22%E5%85%BC%E5%AE%B9kotlin%E8%AF%AD%E6%B3%95%E9%85%8D%E7%BD%AE)
