### ISSUE TITLE
项目依赖库以后有以下提示信息

### ISSUE THREAD

**Issue by Jack0971** [xuexiangjys/XAOP#11]
WARNING: API 'variant.getJavaCompile()' is obsolete and has been replaced with 'variant.getJavaCompileProvider()'.
It will be removed at the end of 2019.
For more information, see https://d.android.com/r/tools/task-configuration-avoidance.
To determine what is calling variant.getJavaCompile(), use -Pandroid.debug.obsoleteApi=true on the command line to display more information.
Affected Modules: app

**Comment by xuexiangjys** [comment]
这个不影响使用，晚些时间我将修复一下。可暂时先使用3.2.1代替：
```
dependencies {
        classpath 'com.android.tools.build:gradle:3.2.1'
    }
```

**Comment by xuexiangjys** [comment]
这个问题已经修复了，不过考虑到暂时不影响使用，我就暂时先不发版本了：
e8203f5a0b1e12e733bc8f6d23d25c5ff0677142
