### ISSUE TITLE
classpath 'com.github.xuexiangjys.XAOP:xaop-plugin:1.0.5' 拉不下来

### ISSUE THREAD

**Issue by Warlock1994** [xuexiangjys/XAOP#12]
![image](https://user-images.githubusercontent.com/21231664/67646428-145c8200-f969-11e9-91ed-f566bcc5e11d.png)

**Comment by xuexiangjys** [comment]
![image](https://user-images.githubusercontent.com/15059629/67646505-5e456800-f969-11e9-9756-5c9bb6304042.png)
文档字写那么大不看的吗？？？？？

**Comment by RXlung** [comment]
有的repositories 可能也出错
repositories {
        google()
        maven { url "http://jcenter.bintray.com"}
        mavenCentral()
        maven { url 'https://jitpack.io' }
    }

**Comment by RXlung** [comment]
有的repositories 可能也出错 
我的这样是成功的：
repositories {
google()
maven { url "http://jcenter.bintray.com"}
mavenCentral()
maven { url 'https://jitpack.io' }
}
