### ISSUE TITLE
引用了这个插件开发运行时显示R文件被占用

### ISSUE THREAD

**Issue by traywangjun** [xuexiangjys/XAOP#15]
app\build\intermediates\compile_and_runtime_not_namespaced_r_class_jar\baiduDebug\R.jar: 另一个程序正在使用此文件，进程无法访问。

**Comment by xuexiangjys** [comment]
windows的AS问题，和框架没有任何关系，clean一下就行了

**Comment by traywangjun** [comment]
主要是clean了过一会又不行了

**Comment by xuexiangjys** [comment]
你AS的版本是多少?

**Comment by traywangjun** [comment]
3.6.2

**Comment by ichapter** [comment]
同遇到，请问是怎么解决的？

**Comment by minveYu** [comment]
> app\build\intermediates\compile_and_runtime_not_namespaced_r_class_jar\baiduDebug\R.jar: 另一个程序正在使用此文件，进程无法访问。

估计gradle是5.6那种，更改gradle-wrapper.properties 降为4.8，项目的build.gradle 用3.6以下的，删除项目目录的gradle文件夹，iml，gradew之类的文件，让as重新构建

**Comment by traywangjun** [comment]
> > app \ build \ intermediates \ compile_and_runtime_not_namespaced_r_class_jar \ baiduDebug \ R.jar：另一个程序正在使用此文件，无法访问。
> 
> 估计gradle是5.6种类，更改gradle-wrapper.properties降为4.8，项目的build.gradle用3.6以下的，删除项目目录的gradle文件夹，iml，gradew之类的文件，让重新构建

有点强迫症 用的都是最新版的gradle，感谢回复

**Comment by yangjieK** [comment]
@traywangjun  gradle后来解决了么?我用的也是 3.6.2

**Comment by GitJoBo** [comment]
这和单个版本没关系，as版本和gradle不匹配导致的；都用新版没问题
