### ISSUE TITLE
按照配置没有起作用

### ISSUE THREAD

**Issue by spysoos** [xuexiangjys/XAOP#18]
按照配置没有起作用 ，我的工程是java+kotlin混编，有什么需要特别配置的吗？

**Comment by xuexiangjys** [comment]
你没有起作用,应该把你的配置详细写下来,然后和文档或者demo对比一下,是不是哪里漏了,你什么都不说,你让我怎么帮你?盲猜吗?
kotlin配置麻烦不要漏了:
https://github.com/xuexiangjys/XAOP#22%E5%85%BC%E5%AE%B9kotlin%E8%AF%AD%E6%B3%95%E9%85%8D%E7%BD%AE

**Comment by spysoos** [comment]
谢谢 可以了 确实是kotlin配置的问题
