### ISSUE TITLE
在引入XAOP时出错

### ISSUE THREAD

**Issue by NoMoneyError** [xuexiangjys/XAOP#19]
![360截图1757111693114131](https://user-images.githubusercontent.com/54740373/89260362-b333ae80-d65e-11ea-8868-c757a5378a04.png)
在引入classpath 'com.github.xuexiangjys.XAOP:xaop-plugin:1.0.5'时报错
Could not find com.github.xuexiangjys.XAOP:xaop-plugin:1.0.5.

**Comment by xuexiangjys** [comment]
仔细看文档行不行？？？？
https://github.com/xuexiangjys/XAOP#21android-studio%E5%AF%BC%E5%85%A5%E6%96%B9%E6%B3%95%E6%B7%BB%E5%8A%A0gradle%E4%BE%9D%E8%B5%96
