### ISSUE TITLE
gradle:4.0.1 排坑

### ISSUE THREAD

**Issue by zhangxu2814** [xuexiangjys/XAOP#22]
现象：
1. 运行后会在根目录生成 ajcore.20202xxxxx.text
2. 在debug 模式下 发现无法进入 SingleClickAspectJ.aroundJoinPoint()
3.项目中引用了第三方Kotlin工具类。
解决思路：
1.先按Kotlin项目进行配置。=》编译失败：Cannot cast object 'com.android.build.gradle.internal.pipeline.TransformTask
2. 升级  classpath 'com.hujiang.aspectjx:gradle-android-plugin-aspectjx:**2.0.10**' =》Cause: zip file is empty
3.添加  aspectjx {
        enabled true
        include '项目的 applicationId'
    }
最终运行成功，可正常进入debug。

**Comment by xuexiangjys** [comment]
非常感谢排坑,已更新至readme中
