### ISSUE TITLE
Koltin编译问题

### ISSUE THREAD

**Issue by lisper-ip** [xuexiangjys/XAOP#27]
新创建的项目按照文章上的说明可以编译通过，但是以前的项目 加了相同的配置就编译失败了 麻烦您给看一下 
<img width="1119" alt="截屏2021-05-28 下午4 07 59" src="https://user-images.githubusercontent.com/67527587/119951801-f173d300-bfce-11eb-8778-5d20d85db519.png">
<img width="1207" alt="截屏2021-05-28 下午4 08 13" src="https://user-images.githubusercontent.com/67527587/119951822-f6388700-bfce-11eb-8d1d-e4b98559f058.png">
<img width="768" alt="截屏2021-05-28 下午4 09 06" src="https://user-images.githubusercontent.com/67527587/119951912-0badb100-bfcf-11eb-926e-b19ccd42507f.png">
<img width="632" alt="截屏2021-05-28 下午4 09 37" src="https://user-images.githubusercontent.com/67527587/119951995-2122db00-bfcf-11eb-9c85-9c060964f4af.png">

**Comment by xuexiangjys** [comment]
gradle版本不兼容吧，升级一下gradle的版本
