### ISSUE TITLE
组件化项目按照上面配置 plugin无法生效

### ISSUE THREAD

**Issue by gaoxu19930112** [xuexiangjys/XAOP#28]
组件化项目按照上面配置 plugin无法生效

**Comment by xuexiangjys** [comment]
请提供有用的信息

**Comment by gaoxu19930112** [comment]
我在根目录里设置classpath 'com.github.xuexiangjys.XAOP:xaop-plugin:1.1.0' Base组件里引入了远程库api 'com.github.xuexiangjys.XAOP:xaop-runtime:1.1.0', 并在所有组件库和壳app里都设置了apply plugin: 'com.xuexiang.xaop'  并在application里进行了初始化 但是在组件里使用或者在app项目里使用都没有用,无法进入到切面里

**Comment by xuexiangjys** [comment]
不好意思,我已经试过了,组件化使用是没有任何问题的,我觉得是你使用的方式有问题.
9be86c74bc8517701b636d4664ac01c7d4830745

**Comment by zy19880309** [comment]
我也遇到了同样的问题，在appmodule里是正常的，在其他module里怎么配置都不生效，如果作者有组件化生效的方案不妨发出来看一看
