### ISSUE TITLE
可以增加lamda表达式支持吗

### ISSUE THREAD

**Issue by s949492225** [xuexiangjys/XAOP#3]

**Comment by xuexiangjys** [comment]
没理解你的需求，能否增加多一些描述需求的信息

**Comment by s949492225** [comment]
你这个在使用lambda语法时无法支持接口的切面,比如view的OnClickListener,runable或者其他的接口,
如果你不理解lambda的话,可以百度下,,无意冒犯,只是说下这种普遍的需求,我个人觉得lambda大家使用的比较多

**Comment by xuexiangjys** [comment]
lambda表达式只是一种语法糖而已，和普通的没有任何区别，AspectJ本身就是支持的，你如果不会的话，我已经增加了示例代码。https://github.com/xuexiangjys/XAOP/blob/master/app/src/main/java/com/xuexiang/xaopdemo/MainActivity.java
