### ISSUE TITLE
切片没生效

### ISSUE THREAD

**Issue by 1149452014** [xuexiangjys/XAOP#31]
配置都对了，一个切片都没生效，啥情况

**Comment by xuexiangjys** [comment]
你如何判定你配置对了呢？

**Comment by 1149452014** [comment]
经过反复测试是和landroidx.lifecycle:lifecycle-viewmodel有冲突，引入lifecycle-viewmodel就不生效

**Comment by 1149452014** [comment]
> 你如何鉴别你的配置对了呢？

经过测试发现是和landroidx.lifecycle:lifecycle-viewmodel有冲突，引入lifecycle-viewmodel后不再生效

**Comment by xuexiangjys** [comment]
androidx.lifecycle:lifecycle-viewmodel里面有kotlin的代码，需要做kotlin代码的兼容
