### ISSUE TITLE
项目根目录下有一堆 ajcore 的日志文件是这个库干的不？我是服了，真垃圾

### ISSUE THREAD

**Issue by dazeGitHub** [xuexiangjys/XAOP#34]
![Snipaste_2023-03-13_10-38-41](https://user-images.githubusercontent.com/17785036/224595839-c5816f66-28ae-4839-8631-ddcb4c9b956b.png)

**Comment by xuexiangjys** [comment]
觉得垃圾就别用,没人逼你,真的
