### ISSUE TITLE
您好 有个需求想请教一下

### ISSUE THREAD

**Issue by yuanchenghao** [xuexiangjys/XAOP#4]
怎么能算出我在某个页面停留时间和停留的位置呢 不太懂 不知道aop的方式该怎么搞

**Comment by xuexiangjys** [comment]
可以使用AspectJ，在需要监控的页面上打桩，记录下开启的时间，又或者使用Javassist在特定的方法前记录下时间，比如说activity的oncreate或者fragment的oncreateview。
