### ISSUE TITLE
一点过分的要求

### ISSUE THREAD

**Issue by guozhiqiang123** [xuexiangjys/XAOP#6]
能不能把这个功能加进去啊，感觉在开发中很常用
http://mp.weixin.qq.com/s?__biz=MzA5MzI3NjE2MA==&mid=2650243807&idx=1&sn=b36a5eabd3198540b0976231f54b28f1&chksm=886373b0bf14faa6a494cba650e4c5f98dfea8a21f0bb5b820b66345e424e7e48ee016daac5d&scene=38#wechat_redirect

**Comment by xuexiangjys** [comment]
使用`@Intercept`就可以实现了

**Comment by guozhiqiang123** [comment]
登录成功后接着跳转用@Intercept也可以实现吗

**Comment by guozhiqiang123** [comment]
有使用demo吗 我借鉴一下

**Comment by xuexiangjys** [comment]
暂时没有，晚上我回去加一下

**Comment by guozhiqiang123** [comment]
好的 辛苦啦

**Comment by xuexiangjys** [comment]
详细参见：
162b97cc783183feaec464d502baca070be50476

**Comment by guozhiqiang123** [comment]
嗯嗯
