### ISSUE TITLE
一个小建议

### ISSUE THREAD

**Issue by guozhiqiang123** [xuexiangjys/XAOP#7]
大神 能不能提供个支持设置全局所有点击为SingleClick啊？如果某个特殊的不需要SingleClick的也可以通过某个注解取消。其实绝大多数数按钮的点击都应该是不可被快速点击的，如果提供这样的方案的话，开发的时候会方便很多。

**Comment by xuexiangjys** [comment]
这种是肯定实现不了的

**Comment by BigTimo** [comment]
刚好之前也在做同样的事情。建议如下
>public @interface SingleClick {
    //建议添加 一个boolean值来控制是否启用全局的防抖点击,默认开启，符合绝大多数情况。
    boolean isGlobal() default true;
}

在ClikUtils中
>public static boolean isFastDoubleClick(View v, boolean isGlobal, long intervalMillis) {
        long time = System.currentTimeMillis();
        int viewId = v.getId();
        long timeD = Math.abs(time - sLastClickTime);
        if (timeD < intervalMillis) {
            if (isGlobal) {//如果是全局开启，则认为是多次点击
                return true;
            } else {
                if (viewId == sLastClickViewId) {
                    return true;
                } else {
                    sLastClickTime = time;
                    sLastClickViewId = viewId;
                    return false;
                }
            }
        } else {
            sLastClickTime = time;
            sLastClickViewId = viewId;
            return false;
        }
    }
